"""multi session treatment tracking and refund requests

Revision ID: 1dcae23aa659
Revises: 986810d62812
Create Date: 2026-09-19 17:53:41.763443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dcae23aa659'
down_revision: Union[str, None] = '986810d62812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicit enum-type creation, same reason/pattern as
    # 986810d62812_clinical_intake_and_visit_documents.py: add_column/
    # create_table auto-creates the Postgres TYPE only inside CREATE TABLE,
    # not reliably across both new tables below without naming it first.
    refundrequestedbytype = postgresql.ENUM('AI_RECEPTIONIST', 'PATIENT_PORTAL', 'STAFF', name='refundrequestedbytype')
    refundrequestedbytype.create(op.get_bind(), checkfirst=True)
    refundrequeststatus = postgresql.ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='refundrequeststatus')
    refundrequeststatus.create(op.get_bind(), checkfirst=True)
    sessionvisitstatus = postgresql.ENUM('PLANNED', 'SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='sessionvisitstatus')
    sessionvisitstatus.create(op.get_bind(), checkfirst=True)

    op.create_table('refund_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_type', postgresql.ENUM('AI_RECEPTIONIST', 'PATIENT_PORTAL', 'STAFF', name='refundrequestedbytype', create_type=False), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('calculation_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', postgresql.ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='refundrequeststatus', create_type=False), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('session_index', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='sessionvisitstatus', create_type=False), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('products_used', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('session_note', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default on all three new NOT NULL columns below — required so
    # existing rows (procedures/treatment_plan_items already in the table)
    # backfill to the same "1 session, no checklist" behavior every
    # pre-existing single-visit procedure already has today, rather than
    # failing the migration outright.
    op.add_column('procedures', sa.Column('default_session_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('procedures', sa.Column('default_checklist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('treatment_plan_items', sa.Column('sessions_total', sa.Integer(), server_default='1', nullable=False))
    # NOTE: autogenerate also detected the same pre-existing drift excluded
    # in 986810d62812 (staff_conversations/staff_messages FK naming,
    # users.work_schedule NOT NULL) — deliberately excluded here too.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_plan_items', 'sessions_total')
    op.drop_column('procedures', 'default_checklist')
    op.drop_column('procedures', 'default_session_count')
    op.drop_table('session_visits')
    op.drop_table('refund_requests')
    # ### end Alembic commands ###

    postgresql.ENUM(name='sessionvisitstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='refundrequeststatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='refundrequestedbytype').drop(op.get_bind(), checkfirst=True)
