"""clinical intake and visit documents

Revision ID: 986810d62812
Revises: a7b8c9d0e1f2
Create Date: 2026-09-19 16:56:44.951169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '986810d62812'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLAlchemy auto-creates an Enum's Postgres TYPE when it's part of a
    # CREATE TABLE, but NOT when added to an existing table via add_column —
    # create the three new enum types explicitly first (create_type=False on
    # the column definitions below then just references them), same pattern
    # as c671868ced69_user_role_enum.py.
    visitdocumenttype = postgresql.ENUM('INTAKE_SUMMARY', name='visitdocumenttype')
    visitdocumenttype.create(op.get_bind(), checkfirst=True)
    visitdocumentgeneratedby = postgresql.ENUM('AI_RECEPTIONIST', 'STAFF', 'SYSTEM', name='visitdocumentgeneratedby')
    visitdocumentgeneratedby.create(op.get_bind(), checkfirst=True)
    pregnancystatus = postgresql.ENUM('NOT_APPLICABLE', 'PREGNANT', 'NURSING', 'NOT_PREGNANT_OR_NURSING', 'DECLINED_TO_ANSWER', name='pregnancystatus')
    pregnancystatus.create(op.get_bind(), checkfirst=True)

    op.create_table('visit_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('document_type', postgresql.ENUM('INTAKE_SUMMARY', name='visitdocumenttype', create_type=False), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('generated_by', postgresql.ENUM('AI_RECEPTIONIST', 'STAFF', 'SYSTEM', name='visitdocumentgeneratedby', create_type=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_to_patient_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_to_doctor_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_to_receptionist_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consent_documents', sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('consent_documents', sa.Column('treatment_plan_notes', sa.Text(), nullable=True))
    op.add_column('consent_documents', sa.Column('file_url', sa.String(length=1000), nullable=True))
    op.add_column('consent_templates', sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patients', sa.Column('pregnancy_status', postgresql.ENUM('NOT_APPLICABLE', 'PREGNANT', 'NURSING', 'NOT_PREGNANT_OR_NURSING', 'DECLINED_TO_ANSWER', name='pregnancystatus', create_type=False), nullable=True))
    op.add_column('patients', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('regular_physician_name', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('regular_physician_phone', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('patients', sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True))
    # NOTE: autogenerate also detected pre-existing drift unrelated to this
    # change (staff_conversations/staff_messages FK naming, users.work_schedule
    # NOT NULL) — deliberately excluded from this migration; not this
    # feature's concern and the NOT NULL alter risks failing on existing rows.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'weight_kg')
    op.drop_column('patients', 'height_cm')
    op.drop_column('patients', 'regular_physician_phone')
    op.drop_column('patients', 'regular_physician_name')
    op.drop_column('patients', 'emergency_contact_relationship')
    op.drop_column('patients', 'occupation')
    op.drop_column('patients', 'pregnancy_status')
    op.drop_column('consent_templates', 'sections')
    op.drop_column('consent_documents', 'file_url')
    op.drop_column('consent_documents', 'treatment_plan_notes')
    op.drop_column('consent_documents', 'sections')
    op.drop_table('visit_documents')
    # ### end Alembic commands ###

    postgresql.ENUM(name='pregnancystatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='visitdocumentgeneratedby').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='visitdocumenttype').drop(op.get_bind(), checkfirst=True)
